# Generated by Django 5.2.12 on 2026-06-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_project_github_link_project_live_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='categories',
            field=models.CharField(db_index=True, default='Uncategorized', help_text='Separate categories with commas', max_length=255),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='experience',
            name='categories',
            field=models.CharField(db_index=True, default='Uncategorized', help_text='Separate categories with commas', max_length=255),
        ),
        migrations.AlterField(
            model_name='experience',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='faq',
            name='categories',
            field=models.CharField(db_index=True, default='Uncategorized', help_text='Separate categories with commas', max_length=255),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(db_index=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='project',
            name='categories',
            field=models.CharField(db_index=True, default='Uncategorized', help_text='Separate categories with commas', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='skill',
            name='categories',
            field=models.CharField(db_index=True, default='Uncategorized', help_text='Separate categories with commas', max_length=255),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
